### ISSUE TITLE
Hello, I have some problems

### ISSUE THREAD

**Issue by AliYa-chen** [cassiompf/lol-authenticator#1]
![image](https://user-images.githubusercontent.com/77602247/149987780-12375e3d-6c81-45ec-9c91-df5442a433a0.png)
I encountered these mistakes
How to apply it in hero League China

**Comment by cassiompf** [comment]
This happened because the port number size is not always 5. I'll fix that soon!

**Comment by cassiompf** [comment]
I just fixed it, you can use git pull to update the repository on your computer
