### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by AliYa-chen** [cassiompf/lol-authenticator#2]
The hero alliance in China cannot be used

![image](https://user-images.githubusercontent.com/77602247/151704074-d9e57d62-5a24-433c-aa12-1265f09f0843.png)
How do I run it?

**Comment by cassiompf** [comment]
> How do I run it?

Hi! It doesn't work for Chinese servers. I would have to implement a new feature, because probably things work differently in league of legends chinese
